version: '3.9'

services:
  app:
#    image: ghcr.io/muhammadaminusmonov/lost_laptop:latest
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: