name: FastAPI CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 Login to GHCR
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 🐳 Build image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      # 🚀 Push image
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

      # 🔥 DEPLOY TO SERVER
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            docker pull ghcr.io/${{ github.repository }}:latest

            docker stop fastapi_app || true
            docker rm fastapi_app || true

            docker run -d \
              --name fastapi_app \
              -p 8000:8000 \
              --restart always \
              ghcr.io/${{ github.repository }}:latest